# Generated by Django 4.2.1 on 2023-05-19 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Administrateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
                ("color", models.CharField(max_length=255)),
                ("mileage", models.IntegerField()),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                ("prenom", models.CharField(max_length=50)),
                ("telephone", models.CharField(max_length=50, unique=True)),
                ("image", models.CharField(max_length=50)),
                ("login", models.CharField(max_length=50, unique=True)),
                ("mot_de_passe", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marque", models.CharField(max_length=50)),
                ("modele", models.CharField(max_length=50)),
                ("prix_par_jour", models.DecimalField(decimal_places=2, max_digits=10)),
                ("photo", models.BinaryField()),
                (
                    "id_admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cars.administrateur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_reservation", models.DateField()),
                (
                    "id_admin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cars.administrateur",
                    ),
                ),
                (
                    "id_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cars.client"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetailsReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_recuperation", models.DateField()),
                ("date_retour", models.DateField()),
                (
                    "id_reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cars.reservation",
                    ),
                ),
                (
                    "id_vehicule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cars.vehicule"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="client",
            name="id_utilisateur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cars.utilisateur"
            ),
        ),
        migrations.AddField(
            model_name="administrateur",
            name="id_utilisateur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cars.utilisateur"
            ),
        ),
    ]
